name: jstoll
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53533
title: Jan Christian Stoll
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebeded'
    - '#0f1c16'
    - '#144746'
    - '#53716d'
    - '#70a8a9'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
