name: jstoll
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53533
title: Jan Christian Stoll
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#003400'
    - '#016100'
    - '#6daf01'
    - '#abdf02'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
