name: jstoll
favicon: null
layout_spectrum: 0.00165
typography_spectrum: 0.53533
title: Jan Christian Stoll
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fb85c'
    - '#689f4b'
    - '#12333c'
    - '#295148'
    - '#3a7535'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
